### ISSUE TITLE
Unrelated issue

### ISSUE THREAD

**Issue by pizzamaker** [sstangl/esperanto-x-system-enabler#2]
It would be nice if you could update this great add-on https://addons.mozilla.org/en-US/firefox/addon/%C4%89apelisto/?src=search

Ĉapelisto no longer works in recent Firefox versions, and was last updated in 2009. Could you take over it? Pretty please?

**Comment by sstangl** [comment]
Mi retmesaĝis ĝian aŭtoron, kiu sugestis, ke ni povas ripari ĝin per ĝia github-a paĝo, https://github.com/eiriarte/cxapelisto.

Ŝajnas, ke ĝi ankoraŭ bezonas XUL, sed butonoj en la nun-versiaj fajrvulpoj devas esti ĉe la supero apud la serĉilo.

Kiam ajn mi havas la tempon, mi provos helpi. Dankon.

**Comment by pizzamaker** [comment]
Dankon! Mi kreis eron tie: https://github.com/eiriarte/cxapelisto/issues/1
